name: Python Linting (Push)
on: [push, pull_request]
jobs:
  lint_code:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - run: pip install -r requirements.txt
     - name: Python Linter
       uses: sunnysid3up/python-linter@master
       with:
         source: "pages"
