[client]
showErrorDetails = false
toolbarMode = "viewer"

[runner]
magicEnabled = true

[server]
port = 8501

[browser]
serverPort = 8501

[theme]
base = "dark"
primaryColor = "#41c9e2"
backgroundColor="#f7eedd"
secondaryBackgroundColor="#FFECD6"
textColor="#3559E0"