[client]
showErrorDetails = false
toolbarMode = "viewer"
showSidebarNavigation = true

[runner]
magicEnabled = true

[server]
port = 8501

[browser]
serverPort = 8501

[theme]
base = "light"
primaryColor = "#41c9e2"
backgroundColor="#f5f5f7"
secondaryBackgroundColor="#cbcbcd"
textColor="#1d1d1f"